/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Goldbar.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Goldbar(props) {
  const { nodes, materials } = useGLTF('models/Goldbar.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[0, -.5, 0]} scale={[1.228, 1, 0.69]} />
    </group>
  )
}

useGLTF.preload('models/Goldbar.glb')
